"""allow duplicate document external identifiers

Revision ID: a9945f6ad485
Revises: d4925fa34c8a
Create Date: generated by Day 5 corrective migration

"""

from typing import Sequence, Union

from alembic import op


revision: str = 'a9945f6ad485'
down_revision: Union[str, Sequence[str], None] = 'd4925fa34c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Allow repeated external document and chunk IDs."""

    op.execute(
        """
        ALTER TABLE documents
        DROP CONSTRAINT IF EXISTS uq_documents_document_code
        """
    )

    op.execute(
        """
        ALTER TABLE document_chunks
        DROP CONSTRAINT IF EXISTS uq_document_chunks_chunk_code
        """
    )

    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_documents_document_code
        ON documents (document_code)
        """
    )

    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_document_chunks_chunk_code
        ON document_chunks (chunk_code)
        """
    )


def downgrade() -> None:
    """Keep downgrade safe with duplicate demo identifiers.

    We intentionally do not recreate the old unique constraints
    because the source demo data contains duplicate external IDs.
    Recreating those constraints would fail on valid demo data.
    """

    op.execute(
        """
        DROP INDEX IF EXISTS ix_document_chunks_chunk_code
        """
    )

    op.execute(
        """
        DROP INDEX IF EXISTS ix_documents_document_code
        """
    )
