"""allow duplicate document codes

Revision ID: d4925fa34c8a
Revises: ea6e629964bc
Create Date: 2026-07-09 10:16:01.671634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4925fa34c8a'
down_revision: Union[str, Sequence[str], None] = 'ea6e629964bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_documents_document_code'), 'documents', type_='unique')
    op.create_index(op.f('ix_documents_document_code'), 'documents', ['document_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_document_code'), table_name='documents')
    op.create_unique_constraint(op.f('uq_documents_document_code'), 'documents', ['document_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
