"""create foundational plant asset and identity tables

Revision ID: e4063517af0f
Revises:
Create Date: 2026-07-08 15:38:49.062987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4063517af0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('plant_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Kolkata', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants')),
    sa.UniqueConstraint('plant_code', name=op.f('uq_plants_plant_code'))
    )
    op.create_index(op.f('ix_plants_deleted_at'), 'plants', ['deleted_at'], unique=False)
    op.create_table('roles',
    sa.Column('role_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name')),
    sa.UniqueConstraint('role_code', name=op.f('uq_roles_role_code'))
    )
    op.create_index(op.f('ix_roles_deleted_at'), 'roles', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_table('areas',
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('area_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_areas_plant_id_plants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas')),
    sa.UniqueConstraint('plant_id', 'area_code', name='uq_areas_plant_id_area_code')
    )
    op.create_index(op.f('ix_areas_deleted_at'), 'areas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_areas_plant_id'), 'areas', ['plant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('systems',
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('system_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_systems_area_id_areas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_systems')),
    sa.UniqueConstraint('area_id', 'system_code', name='uq_systems_area_id_system_code')
    )
    op.create_index(op.f('ix_systems_area_id'), 'systems', ['area_id'], unique=False)
    op.create_index(op.f('ix_systems_deleted_at'), 'systems', ['deleted_at'], unique=False)
    op.create_table('assets',
    sa.Column('system_id', sa.Uuid(), nullable=False),
    sa.Column('asset_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criticality', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=True),
    sa.Column('health_score', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('health_score IS NULL OR (health_score >= 0 AND health_score <= 100)', name='asset_health_score_range'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='asset_risk_score_range'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name=op.f('fk_assets_system_id_systems'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('asset_code', name=op.f('uq_assets_asset_code'))
    )
    op.create_index(op.f('ix_assets_deleted_at'), 'assets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_assets_system_id'), 'assets', ['system_id'], unique=False)
    op.create_table('components',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('component_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_components_asset_id_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_components')),
    sa.UniqueConstraint('asset_id', 'component_code', name='uq_components_asset_id_component_code')
    )
    op.create_index(op.f('ix_components_asset_id'), 'components', ['asset_id'], unique=False)
    op.create_index(op.f('ix_components_deleted_at'), 'components', ['deleted_at'], unique=False)
    op.create_table('sensors',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('sensor_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sensor_type', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_sensors_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_sensors_component_id_components'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensors')),
    sa.UniqueConstraint('sensor_code', name=op.f('uq_sensors_sensor_code'))
    )
    op.create_index(op.f('ix_sensors_asset_id'), 'sensors', ['asset_id'], unique=False)
    op.create_index(op.f('ix_sensors_component_id'), 'sensors', ['component_id'], unique=False)
    op.create_index(op.f('ix_sensors_deleted_at'), 'sensors', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensors_deleted_at'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_component_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_asset_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_components_deleted_at'), table_name='components')
    op.drop_index(op.f('ix_components_asset_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_assets_system_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_deleted_at'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_systems_deleted_at'), table_name='systems')
    op.drop_index(op.f('ix_systems_area_id'), table_name='systems')
    op.drop_table('systems')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_areas_plant_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_deleted_at'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_deleted_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_plants_deleted_at'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
