"""add operational domain tables

Revision ID: ea6e629964bc
Revises: e4063517af0f
Create Date: 2026-07-08 16:46:26.854766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea6e629964bc'
down_revision: Union[str, Sequence[str], None] = 'e4063517af0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_severity', sa.String(length=50), nullable=False),
    sa.Column('evaluation_type', sa.String(length=150), nullable=False),
    sa.Column('source_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_rules')),
    sa.UniqueConstraint('rule_code', name=op.f('uq_compliance_rules_rule_code'))
    )
    op.create_index(op.f('ix_compliance_rules_default_severity'), 'compliance_rules', ['default_severity'], unique=False)
    op.create_index(op.f('ix_compliance_rules_deleted_at'), 'compliance_rules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_compliance_rules_evaluation_type'), 'compliance_rules', ['evaluation_type'], unique=False)
    op.create_table('dataset_snapshots',
    sa.Column('dataset_key', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_snapshots')),
    sa.UniqueConstraint('dataset_key', name=op.f('uq_dataset_snapshots_dataset_key'))
    )
    op.create_index(op.f('ix_dataset_snapshots_deleted_at'), 'dataset_snapshots', ['deleted_at'], unique=False)
    op.create_table('documents',
    sa.Column('document_code', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=150), nullable=False),
    sa.Column('source_group', sa.String(length=150), nullable=True),
    sa.Column('relative_path', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('document_code', name=op.f('uq_documents_document_code'))
    )
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_source_group'), 'documents', ['source_group'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_code', sa.String(length=250), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('source_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('chunk_code', name=op.f('uq_document_chunks_chunk_code'))
    )
    op.create_index(op.f('ix_document_chunks_deleted_at'), 'document_chunks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('asset_health_snapshots',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('source_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_health_snapshots_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_health_snapshots')),
    sa.UniqueConstraint('asset_id', name='uq_asset_health_snapshots_asset_id')
    )
    op.create_index(op.f('ix_asset_health_snapshots_asset_id'), 'asset_health_snapshots', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_health_snapshots_deleted_at'), 'asset_health_snapshots', ['deleted_at'], unique=False)
    op.create_table('compliance_asset_summaries',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('source_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_compliance_asset_summaries_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_asset_summaries')),
    sa.UniqueConstraint('asset_id', name='uq_compliance_asset_summaries_asset_id')
    )
    op.create_index(op.f('ix_compliance_asset_summaries_asset_id'), 'compliance_asset_summaries', ['asset_id'], unique=False)
    op.create_index(op.f('ix_compliance_asset_summaries_deleted_at'), 'compliance_asset_summaries', ['deleted_at'], unique=False)
    op.create_table('compliance_findings',
    sa.Column('finding_code', sa.String(length=100), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('requirement', sa.String(length=500), nullable=False),
    sa.Column('current_status', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('source_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_compliance_findings_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], name=op.f('fk_compliance_findings_rule_id_compliance_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_findings')),
    sa.UniqueConstraint('finding_code', name=op.f('uq_compliance_findings_finding_code'))
    )
    op.create_index(op.f('ix_compliance_findings_asset_id'), 'compliance_findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_compliance_findings_current_status'), 'compliance_findings', ['current_status'], unique=False)
    op.create_index(op.f('ix_compliance_findings_deleted_at'), 'compliance_findings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_compliance_findings_rule_id'), 'compliance_findings', ['rule_id'], unique=False)
    op.create_index(op.f('ix_compliance_findings_severity'), 'compliance_findings', ['severity'], unique=False)
    op.create_table('document_asset_links',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_document_asset_links_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_asset_links_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'asset_id', name=op.f('pk_document_asset_links'))
    )
    op.create_table('maintenance_events',
    sa.Column('event_code', sa.String(length=150), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('source_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_maintenance_events_asset_id_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_events')),
    sa.UniqueConstraint('event_code', name=op.f('uq_maintenance_events_event_code'))
    )
    op.create_index(op.f('ix_maintenance_events_asset_id'), 'maintenance_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_events_deleted_at'), 'maintenance_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_maintenance_events_status'), 'maintenance_events', ['status'], unique=False)
    op.create_table('rca_cases',
    sa.Column('case_code', sa.String(length=150), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('incident_status', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overall_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('source_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_rca_cases_asset_id_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rca_cases')),
    sa.UniqueConstraint('case_code', name=op.f('uq_rca_cases_case_code'))
    )
    op.create_index(op.f('ix_rca_cases_asset_id'), 'rca_cases', ['asset_id'], unique=False)
    op.create_index(op.f('ix_rca_cases_deleted_at'), 'rca_cases', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_rca_cases_detected_at'), 'rca_cases', ['detected_at'], unique=False)
    op.create_index(op.f('ix_rca_cases_incident_status'), 'rca_cases', ['incident_status'], unique=False)
    op.create_index(op.f('ix_rca_cases_severity'), 'rca_cases', ['severity'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_code', sa.String(length=200), nullable=False),
    sa.Column('rca_case_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('source_reference', sa.String(length=250), nullable=True),
    sa.Column('document_type', sa.String(length=150), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('source_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_evidence_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rca_case_id'], ['rca_cases.id'], name=op.f('fk_evidence_rca_case_id_rca_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('evidence_code', name=op.f('uq_evidence_evidence_code'))
    )
    op.create_index(op.f('ix_evidence_deleted_at'), 'evidence', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_evidence_document_id'), 'evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_evidence_rca_case_id'), 'evidence', ['rca_case_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_reference'), 'evidence', ['source_reference'], unique=False)
    op.create_table('maintenance_work_orders',
    sa.Column('work_order_code', sa.String(length=150), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('rca_case_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_role', sa.String(length=200), nullable=True),
    sa.Column('risk_score', sa.SmallInteger(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('source_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_maintenance_work_orders_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rca_case_id'], ['rca_cases.id'], name=op.f('fk_maintenance_work_orders_rca_case_id_rca_cases'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_work_orders')),
    sa.UniqueConstraint('work_order_code', name=op.f('uq_maintenance_work_orders_work_order_code'))
    )
    op.create_index(op.f('ix_maintenance_work_orders_asset_id'), 'maintenance_work_orders', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_deleted_at'), 'maintenance_work_orders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_due_at'), 'maintenance_work_orders', ['due_at'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_maintenance_type'), 'maintenance_work_orders', ['maintenance_type'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_priority'), 'maintenance_work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_rca_case_id'), 'maintenance_work_orders', ['rca_case_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_status'), 'maintenance_work_orders', ['status'], unique=False)
    op.create_table('root_causes',
    sa.Column('cause_code', sa.String(length=150), nullable=False),
    sa.Column('rca_case_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('source_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rca_case_id'], ['rca_cases.id'], name=op.f('fk_root_causes_rca_case_id_rca_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_root_causes')),
    sa.UniqueConstraint('cause_code', name=op.f('uq_root_causes_cause_code'))
    )
    op.create_index(op.f('ix_root_causes_deleted_at'), 'root_causes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_root_causes_rca_case_id'), 'root_causes', ['rca_case_id'], unique=False)
    op.add_column('assets', sa.Column('source_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('assets', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'payload')
    op.drop_column('assets', 'source_order')
    op.drop_index(op.f('ix_root_causes_rca_case_id'), table_name='root_causes')
    op.drop_index(op.f('ix_root_causes_deleted_at'), table_name='root_causes')
    op.drop_table('root_causes')
    op.drop_index(op.f('ix_maintenance_work_orders_status'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_rca_case_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_priority'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_maintenance_type'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_due_at'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_deleted_at'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_asset_id'), table_name='maintenance_work_orders')
    op.drop_table('maintenance_work_orders')
    op.drop_index(op.f('ix_evidence_source_reference'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_rca_case_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_document_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_deleted_at'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_rca_cases_severity'), table_name='rca_cases')
    op.drop_index(op.f('ix_rca_cases_incident_status'), table_name='rca_cases')
    op.drop_index(op.f('ix_rca_cases_detected_at'), table_name='rca_cases')
    op.drop_index(op.f('ix_rca_cases_deleted_at'), table_name='rca_cases')
    op.drop_index(op.f('ix_rca_cases_asset_id'), table_name='rca_cases')
    op.drop_table('rca_cases')
    op.drop_index(op.f('ix_maintenance_events_status'), table_name='maintenance_events')
    op.drop_index(op.f('ix_maintenance_events_deleted_at'), table_name='maintenance_events')
    op.drop_index(op.f('ix_maintenance_events_asset_id'), table_name='maintenance_events')
    op.drop_table('maintenance_events')
    op.drop_table('document_asset_links')
    op.drop_index(op.f('ix_compliance_findings_severity'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_rule_id'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_deleted_at'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_current_status'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_asset_id'), table_name='compliance_findings')
    op.drop_table('compliance_findings')
    op.drop_index(op.f('ix_compliance_asset_summaries_deleted_at'), table_name='compliance_asset_summaries')
    op.drop_index(op.f('ix_compliance_asset_summaries_asset_id'), table_name='compliance_asset_summaries')
    op.drop_table('compliance_asset_summaries')
    op.drop_index(op.f('ix_asset_health_snapshots_deleted_at'), table_name='asset_health_snapshots')
    op.drop_index(op.f('ix_asset_health_snapshots_asset_id'), table_name='asset_health_snapshots')
    op.drop_table('asset_health_snapshots')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_deleted_at'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_source_group'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_dataset_snapshots_deleted_at'), table_name='dataset_snapshots')
    op.drop_table('dataset_snapshots')
    op.drop_index(op.f('ix_compliance_rules_evaluation_type'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_deleted_at'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_default_severity'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    # ### end Alembic commands ###
